<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\SubjectController' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\SubjectServiceInterface.php';
include_once $this->targetDirs[3].'\\src\\Service\\SubjectService.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\Controller.php';
include_once $this->targetDirs[3].'\\src\\Controller\\SubjectController.php';

return $this->services['App\Controller\SubjectController'] = new \App\Controller\SubjectController(new \App\Service\SubjectService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->privates['App\Repository\SubjectRepository'] ?? $this->load(__DIR__.'/getSubjectRepositoryService.php'))));
