<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\UserService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\UserServiceInterface.php';
include_once $this->targetDirs[3].'\\src\\Service\\UserService.php';

return $this->privates['App\Service\UserService'] = new \App\Service\UserService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->privates['App\Repository\UserRepository'] ?? $this->load(__DIR__.'/getUserRepositoryService.php')), ($this->privates['App\Repository\RoleRepository'] ?? $this->load(__DIR__.'/getRoleRepositoryService.php')));
