<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF6JKAri\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF6JKAri/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF6JKAri.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF6JKAri\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerF6JKAri\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'F6JKAri',
    'container.build_id' => '4dcdfaec',
    'container.build_time' => 1522669494,
));
