<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIGnWG1D\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIGnWG1D/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIGnWG1D.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIGnWG1D\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIGnWG1D\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IGnWG1D',
    'container.build_id' => '6d72919e',
    'container.build_time' => 1522661078,
));
